name: chat-system-plugin
version: '1.1.0'
main: org.example.com.chatSystemPlugin.Main
api-version: '1.21'
authors: [ Tiziano ]
description: Make potions without visible particles
commands:
  message:
    description: send message to player
  reply:
    description: reply a earlier message
